name: Release
on:
    push:
        tags:
            - "v*.*.*"
jobs:
    # Extracted from https://github.com/foundry-rs/foundry/blob/master/.github/workflows/release.yml
    release:
        strategy:
            matrix:
                job:
                    - os: macos-latest
                      platform: darwin
                      target: x86_64-apple-darwin
                      arch: amd64
                      svm_target_platform: macosx-amd64
                    - os: macos-latest
                      platform: darwin
                      target: aarch64-apple-darwin
                      arch: arm64
                      svm_target_platform: macosx-aarch64
        name: ${{ matrix.job.target }} (${{ matrix.job.os }})
        runs-on: ${{ matrix.job.os }}
        steps:
                - uses: actions/checkout@v3
                # - name: Apple M1 setup
                #   if: ${{ matrix.job.target == 'aarch64-apple-darwin' }}
                #   run: |
                #     echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
                #     echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)" >> $GITHUB_ENV
                - name: Build binaries
                  run: cargo build --release --target ${{ matrix.job.target }}

